// ai-memory lifecycle hooks extension for Pi/OMP.
// Generated from: ai-memory install-hooks --agent omp
// TOKEN reads from process.env.AI_MEMORY_AUTH_TOKEN (loaded by my-env-loader)

// Auto-generated by `ai-memory install-hooks --agent omp --apply`.
// Edit by re-running the command, not by hand — install-hooks
// will overwrite this file (with a `.bak-<ts>` backup) on each
// re-run.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { homedir } from "node:os";

const SERVER = "https://ai-memory.wyrunning.dpdns.org".replace(/\/+$/, "");
const AGENT = "omp";
const TOKEN: string | null = process.env.AI_MEMORY_AUTH_TOKEN ?? null;


function timeoutSignal(ms: number): AbortSignal | undefined {
  if (typeof AbortSignal === "undefined") return undefined;
  const factory = (AbortSignal as unknown as { timeout?: (ms: number) => AbortSignal }).timeout;
  return factory ? factory(ms) : undefined;
}

function authHeaders(): Record<string, string> {
  return TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {};
}

function findMarker(cwd: string | undefined): string | undefined {
  if (!cwd) return undefined;
  let dir = resolve(cwd);
  const home = homedir();
  while (dir && dir !== dirname(dir)) {
    const marker = join(dir, ".ai-memory.toml");
    if (existsSync(marker)) return marker;
    if (home && dir === home) return undefined;
    dir = dirname(dir);
  }
  return undefined;
}

function tomlKey(text: string, key: string): string | undefined {
  const re = new RegExp(`^\\s*${key}\\s*=\\s*"([^"]*)"`);
  for (const line of text.split(/\r?\n/)) {
    const match = re.exec(line);
    if (match) return match[1];
  }
  return undefined;
}


function repoRootProject(cwd: string | undefined): string | undefined {
  if (!cwd) return undefined;
  try {
    const inside = execFileSync("git", ["-C", cwd, "rev-parse", "--is-inside-work-tree"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (inside !== "true") return undefined;
    const common = execFileSync("git", ["-C", cwd, "rev-parse", "--path-format=absolute", "--git-common-dir"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!common) return undefined;
    const root = dirname(common);
    if (!root || root === dirname(root)) return undefined;
    return basename(root);
  } catch (_e) {
    return undefined;
  }
}
function applyMarkerParams(url: URL, cwd: string | undefined): void {
  const marker = findMarker(cwd);
  if (!marker || !cwd) return;
  url.searchParams.set("cwd", cwd);
  try {
    const body = readFileSync(marker, "utf8");
    const workspace = tomlKey(body, "workspace");
    const project = tomlKey(body, "project");
    const projectStrategy = tomlKey(body, "project_strategy");
    if (workspace) url.searchParams.set("workspace", workspace);
    if (project) url.searchParams.set("project", project);
    if (projectStrategy) url.searchParams.set("project_strategy", projectStrategy);
    if (!project && (projectStrategy === "repo-root" || projectStrategy === "repo_root")) {
      const repoProject = repoRootProject(cwd);
      if (repoProject) url.searchParams.set("project", repoProject);
    }
  } catch (_e) {
  }
}

function sessionID(ctx: any): string | undefined {
  const id = ctx?.sessionManager?.getSessionId?.();
  return typeof id === "string" && id.length > 0 ? id : undefined;
}

function modelName(model: any): string | undefined {
  const name = model?.id ?? model?.name ?? model?.model;
  return typeof name === "string" && name.length > 0 ? name : undefined;
}

function sessionPayload(ctx: any): Record<string, unknown> {
  return {
    sessionID: sessionID(ctx),
    cwd: ctx?.cwd,
    model: modelName(ctx?.model),
  };
}

function stringify(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch (_e) {
    return String(value);
  }
}

function contentToText(content: unknown): string {
  if (content === null || content === undefined) return "";
  if (!Array.isArray(content)) return stringify(content);
  return content
    .map((part: any) => {
      if (typeof part?.text === "string") return part.text;
      if (typeof part?.content === "string") return part.content;
      if (typeof part?.type === "string") return `[${part.type}]`;
      return stringify(part);
    })
    .filter(Boolean)
    .join("\n\n")
    .trim();
}

const startedSessions = new Set<string>();
const handoffChecked = new Set<string>();
const preCompactLast = new Map<string, number>();

function startSession(ctx: any, extra: Record<string, unknown> = {}): void {
  const id = sessionID(ctx);
  if (!id || startedSessions.has(id)) return;
  startedSessions.add(id);
  postHook("session-start", { ...sessionPayload(ctx), ...extra });
}

function postPreCompact(ctx: any): void {
  startSession(ctx);
  const key = sessionID(ctx) || "unknown";
  const now = Date.now();
  const last = preCompactLast.get(key) ?? 0;
  if (now - last < 1000) return;
  preCompactLast.set(key, now);
  postHook("pre-compact", sessionPayload(ctx));
}

function postHook(event: string, payload: Record<string, unknown>): void {
  const url = new URL(`${SERVER}/hook`);
  url.searchParams.set("event", event);
  url.searchParams.set("agent", AGENT);
  applyMarkerParams(url, typeof payload.cwd === "string" ? payload.cwd : undefined);
  try {
    void fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json", ...authHeaders() },
      body: JSON.stringify(payload),
      signal: timeoutSignal(500),
    }).catch(() => undefined);
  } catch (_e) {
    // Fire-and-forget. Hooks must never block the agent.
  }
}

async function fetchHandoff(cwd: string): Promise<string | undefined> {
  const url = new URL(`${SERVER}/handoff`);
  url.searchParams.set("agent", AGENT);
  url.searchParams.set("cwd", cwd);
  applyMarkerParams(url, cwd);
  try {
    const response = await fetch(url, {
      headers: authHeaders(),
      signal: timeoutSignal(1000),
    });
    const text = (await response.text()).trim();
    return text.length > 0 ? text : undefined;
  } catch (_e) {
    return undefined;
  }
}

export default function AiMemoryExtension(api: any): void {
  api.on("session_start", (_event: any, ctx: any) => {
    startSession(ctx);
  });

  api.on("before_agent_start", async (event: any, ctx: any) => {
    startSession(ctx);
    postHook("user-prompt", {
      ...sessionPayload(ctx),
      prompt: event?.prompt,
      imageCount: Array.isArray(event?.images) ? event.images.length : undefined,
    });

    const id = sessionID(ctx);
    if (!id || handoffChecked.has(id)) return;
    handoffChecked.add(id);
    const handoff = await fetchHandoff(ctx?.cwd ?? "");
    if (!handoff) return;
    return {
      message: {
        customType: "ai-memory-handoff",
        content: handoff,
        display: false,
        attribution: "agent",
      },
    };
  });

  api.on("tool_call", (event: any, ctx: any) => {
    startSession(ctx);
    postHook("pre-tool-use", {
      ...sessionPayload(ctx),
      tool: event?.toolName,
      callID: event?.toolCallId,
      args: event?.input,
    });
  });

  api.on("tool_result", (event: any, ctx: any) => {
    startSession(ctx);
    postHook("post-tool-use", {
      ...sessionPayload(ctx),
      tool: event?.toolName,
      callID: event?.toolCallId,
      args: event?.input,
      output: contentToText(event?.content),
      details: event?.details,
      isError: event?.isError,
    });
  });

  api.on("session_before_compact", (_event: any, ctx: any) => {
    postPreCompact(ctx);
  });

  api.on("session.compacting", (_event: any, ctx: any) => {
    postPreCompact(ctx);
  });

  api.on("agent_end", (_event: any, ctx: any) => {
    startSession(ctx);
    postHook("stop", sessionPayload(ctx));
  });

  api.on("session_shutdown", (_event: any, ctx: any) => {
    startSession(ctx);
    postHook("session-end", sessionPayload(ctx));
  });
}

